content:
  - name: menu
    label: Menu Items
    type: file
    path: 'menu.json'
    fields:
      - name: name
        label: Item Name
        type: string
      - name: price
        label: Price
        type: number
      - name: description
        label: Description
        type: text
      - name: vegan
        label: Vegan
        type: boolean
      - name: dairy
        label: Contains Dairy
        type: boolean
      - name: glutenfree
        label: Gluten-Free
        type: boolean
      - name: peanuts
        label: Contains Peanuts
        type: boolean
      - name: category
        label: Category
        type: select
        options:
          - Snacks
          - Desserts
          - Drinks
