settings:
  hide: true
  content:
    merge: true # preserve config
components:
  item:
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.name}"
    fields:
      - name: name
        label: Name
        type: string
      - name: description
        label: Description
        type: text
      - name: price
        label: Price
        type: number
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [vegan, dairy, no-gluten, peanuts]
content:
  - name: info
    label: Info
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Description
        type: string
      - name: about
        label: About
        type: text
      - name: hours
        label: Hours
        type: object
        fields:
          - name: weekday
            label: Weekdays
            type: text
          - name: weekend
            label: Weekends
            type: text
      - name: address
        label: Address
        type: text
      - name: phone
        label: Phone
        type: string
  - name: menu
    label: Menu
    type: file
    path: _data/menu.json
    fields:
      - name: savory
        component: item
        label: Savory
      - name: sweet
        component: item
        label: Sweet
      - name: drinks
        component: item
        label: Drinks
