settings:
  hide: true
  content:
    merge: true # preserve config
components:
  item:
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.name}"
    fields:
      - name: name
        label: Name
        type: string
      - name: description
        label: Description
        type: text
      - name: price
        label: Price
        type: number
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [vegan, dairy, no-gluten, peanuts]
content:
  - name: info
    label: Info
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: about
        label: About
        type: text
  - name: menu
    label: Menu
    type: file
    path: _data/menu.json
    fields:
      - name: snacks
        component: item
        label: Snacks
      - name: desserts
        component: item
        label: Desserts
      - name: drinks
        component: item
        label: Drinks
