settings:
  hide: true
components:
  item:
    label: Menu Item
    type: object
    fields:
      - name: name
        label: Name
        type: string
      - name: description
        label: Description
        type: text
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [Vegan, Dairy, Gluten-Free, Peanuts]
      - name: price
        label: Price
        type: number
content:
  - name: info
    label: Info
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: menu
    label: Menu
    type: file
    path: menu.json
    fields:
      - name: snacks
        component: item
        label: Snacks
        type: object
        list: true
      - name: desserts
        component: item
        label: Desserts
        type: object
        list: true
      - name: drinks
        component: item
        label: Drinks
        type: object
        list: true
