title: Govinda’s Montreal
about: Transcendental, karma-free, sattvic, cooked fresh with love and devotion.
  | Transcendantal, sans karma, sāttvique, cuisiné frais avec amour et dévotion.
description: Bilingual restaurant menu
url: https://yourusername.github.io/your-repo-name
markdown: kramdown
